server:
  port: 8081

spring:
  application:
    name: grain-platform-backend
  datasource:
    url: jdbc:mysql://localhost:3306/grain_env_predict?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci&serverTimezone=Asia/Shanghai
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/schema.sql

mybatis:
  type-aliases-package: com.grain.platform.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
